// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCBsNvwEk4iRXD27KAHPw-aP7t4rnAfE',
    appId: '1:357148531101:web:f1afd7c473040e4d797774',
    messagingSenderId: '357148531101',
    projectId: 'urclip-mvp',
    authDomain: 'urclip-mvp.firebaseapp.com',
    storageBucket: 'urclip-mvp.firebasestorage.app',
    measurementId: 'G-XT22GPEW35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0i5NxwyQTcOhsn9NJi2MFRODfUi13Uw',
    appId: '1:357148531101:android:c97d640968efda6e797774',
    messagingSenderId: '357148531101',
    projectId: 'urclip-mvp',
    storageBucket: 'urclip-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUaOzdzjvzpv4JndcF6MT-ojU0gCx2b6s',
    appId: '1:357148531101:ios:c51c55c6fc580a17797774',
    messagingSenderId: '357148531101',
    projectId: 'urclip-mvp',
    storageBucket: 'urclip-mvp.firebasestorage.app',
    iosBundleId: 'com.example.urclipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUaOzdzjvzpv4JndcF6MT-ojU0gCx2b6s',
    appId: '1:357148531101:ios:c51c55c6fc580a17797774',
    messagingSenderId: '357148531101',
    projectId: 'urclip-mvp',
    storageBucket: 'urclip-mvp.firebasestorage.app',
    iosBundleId: 'com.example.urclipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkCBsNvwEk4iRXD27KAHPw-aP7t4rnAfE',
    appId: '1:357148531101:web:ff12c0a2dd9e794a797774',
    messagingSenderId: '357148531101',
    projectId: 'urclip-mvp',
    authDomain: 'urclip-mvp.firebaseapp.com',
    storageBucket: 'urclip-mvp.firebasestorage.app',
    measurementId: 'G-DD47CY1DMV',
  );
}
